### ISSUE TITLE
Add test data to `tests/assets`

### ISSUE THREAD

**Issue by simonbowly** [simonbowly/grblogtools#11]
glass4 relaxation is too easy and we have no pure LPs, so there is currently no simplex/barrier log data in the repo for testing. Would like to add this to the regression tests before changing this part of the parser.

**Comment by simonbowly** [comment]
Cases currently handled:
- [x] (glass 4) simple MIP with no visible relaxation
- [x] pure LP with simplex
- [x] pure LP with barrier
- [x] pure LP with concurrent?
- [x] MIP with a hard relaxation
- [x] pure QP
- [x] MIQCP (nonconvex)

Future cases:
- [ ] concurrent MIP
- [ ] multiobjective
- [ ] multiscenario
- [ ] grbtune

**Comment by simonbowly** [comment]
We should add one log for each example above to `tests/assets`. Examples should be from public instance libraries.

**Comment by maliheha** [comment]
Added three LP examples to the master (in [c4114a3...](https://github.com/simonbowly/grblogtools/commit/c4114a38d1dbca1db2bf472f38afec993513feeb))

**Comment by simonbowly** [comment]
Closing this, I think we have a good range now
